apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: {{ .Values.name }}
spec:
  containers:
  - image: {{ .Values.image }}
    name: {{ .Values.name }}
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
